
name = "z-messages-bot"
main = "cloudflare-workflow.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[[workflows]]
binding = "Z_MESSAGES_WORKFLOW"
class_name = "ZMessagesWorkflow"

[env.production]
name = "z-messages-bot-prod"

[env.staging]
name = "z-messages-bot-staging"
